### ISSUE TITLE
Add `module.exports` to the main module

### ISSUE THREAD

**Issue by FlyingDR** [dword-design/suppress-experimental-warnings#13]
At this moment [main module](https://github.com/dword-design/suppress-experimental-warnings/blob/master/src/index.js) of the project does not include `module.exports` statement. 

Of course it is not needed in this case, there is a practical reason: [Vite](https://vitejs.dev/) reports a warning for modules without `module.exports` statements, effectively polluting logs with: `suppress-experimental-warnings doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

Hope that it is not a big deal to update module in this way.

**Comment by dword-design** [comment]
@FlyingDR How do you use the package with vite? Can you give an example?

**Comment by FlyingDR** [comment]
Sure, I use [SvelteKit](https://kit.svelte.dev/) which, in its turn, uses Vite as a bundler and dev server.

I use Node.js 16 which reports JSON module import as an experimental feature. To remove this warning from Node.js I've added your package to the project and it causes Vite to report a warning, given above.

**Comment by dword-design** [comment]
Ok but how did you add the package to the project? Is it part of the Svelte config and if so, how does it look like?

**Comment by FlyingDR** [comment]
No, I use it in a way, which is recommended by you, for console commands runner:
```bash
#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  node --require=suppress-experimental-warnings console/index.js --help
else
  node --require=suppress-experimental-warnings console/index.js "$@"
fi
```
But it looks like Vite parses contents of the `package.json` and displays a warning even if your package does not involved into SvelteKit run anyhow.

**Comment by dword-design** [comment]
@FlyingDR Ok I dug myself into it and imho this is a vite issue. So, [here](https://github.com/vitejs/vite/blob/134ce6817984bad0f5fb043481502531fee9b1db/packages/vite/src/node/ssr/ssrExternal.ts#L86) is the regex that basically checks if this is a commonjs module and this looks pretty hacky to me. If the package would have require call, the warning would not be thrown anymore. I'd suggest to open an issue in the vite repo to fix it there.

**Comment by FlyingDR** [comment]
@dword-design Thank you for such great research! 

I've seen several similar issues in the Vite repository too, but it looks like that Vite' developers position is that external packages need to be fixed, not their code. But it may be worth opening another issue in Vite. 

It is really strange that they're detecting CJS module by `Object.assign()` which has nothing to do with CJS...

If you prefer to keep your project as it is now - please close the issue.

**Comment by dword-design** [comment]
I'd say close for now and observe what Vite devs are doing.
